# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EaseMobVoice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EaseMobVoice
  platform :ios, '10.0'

  pod 'RxSwift', '5.0.1'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'MJRefresh', '3.3.1'
  pod 'FLAnimatedImage'
  pod 'MBProgressHUD', '1.1.0'
  pod 'Bugly'#, '2.5.2'
  pod 'AgoraRte', :path => '../AgoraRte/AgoraRte_Binary.podspec'
  
  pod 'HyphenateChat'
  pod 'InputBarAccessoryView'
  pod 'ZLPhotoBrowser'
  pod 'SwiftyJSON'
  pod 'MessageKit'
  
 end
